In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import mean_squared_error

In [2]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [3]:
df = pd.read_csv('C:/Users/Ayyan Aftab/Desktop/iv_surface_reconstruct/data/featured_dataset.csv')
df['datetime'] = pd.to_datetime(df['datetime'])
df.head()

,datetime,underlying_price,contract,iv,option_type,strike,hour,minute,day_of_week,date,session_progress,days_to_expiry,moneyness,log_moneyness,dist_from_atm,dist_from_atm_pct,is_ce,strike_rank,iv_neighbor_-2,iv_neighbor_-1,iv_neighbor_+1,iv_neighbor_+2,iv_neighbor_mean,wide_iv_neighbor_mean,iv_lag_1,iv_roll_mean_5,iv_roll_std_5,iv_roll_mean_10,mean_ce_iv,mean_pe_iv
0,2026-01-07 09:15:00,26111.65,NIFTY27JAN2625200CE,0.12662,CE,25200,9,15,2,2026-01-07,0.000000,20.2569,0.965086,-0.035538,911.65,0.034914,1,0.0,NaN,NaN,0.12330,0.11741,0.12330,0.11741,NaN,NaN,NaN,NaN,0.103060,0.143129
1,2026-01-07 09:20:00,26141.40,NIFTY27JAN2625200CE,0.08632,CE,25200,9,20,2,2026-01-07,0.013514,20.2535,0.963988,-0.036676,941.40,0.036012,1,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.12662,NaN,NaN,NaN,0.098762,0.147267
2,2026-01-07 09:25:00,26139.35,NIFTY27JAN2625200CE,0.09147,CE,25200,9,25,2,2026-01-07,0.027027,20.2500,0.964064,-0.036598,939.35,0.035936,1,0.0,NaN,NaN,NaN,0.09514,NaN,0.09514,0.08632,0.106470,0.028496,NaN,0.091175,0.148739
3,2026-01-07 09:30:00,26128.95,NIFTY27JAN2625200CE,0.10860,CE,25200,9,30,2,2026-01-07,0.040541,20.2465,0.964447,-0.036200,928.95,0.035553,1,0.0,NaN,NaN,0.10842,0.11150,0.10842,0.11150,0.09147,0.101470,0.021932,0.101470,0.103672,0.142787
4,2026-01-07 09:35:00,26131.90,NIFTY27JAN2625200CE,0.10462,CE,25200,9,35,2,2026-01-07,0.054054,20.2431,0.964339,-0.036313,931.90,0.035661,1,0.0,NaN,NaN,0.10538,0.12459,0.10538,0.12459,0.10860,0.103252,0.018259,0.103252,0.104564,0.147425

In [4]:
df['iv'].isna().sum()

np.int64(5279)

In [6]:
dates = sorted(df['datetime'].dt.date.unique())

folds = [
    {'name': 'Fold 1', 'train_dates': dates[:9],  'val_dates': dates[9:11]},
    {'name': 'Fold 2', 'train_dates': dates[:10], 'val_dates': dates[10:12]},
]

folds = [
    {'name': 'Fold 1', 'train_dates': dates[:9],  'val_dates': dates[9:11]},
    {'name': 'Fold 2', 'train_dates': dates[:10], 'val_dates': dates[10:12]},
]

In [7]:
def make_holdout(val_df):
    np.random.seed(42)

    available_rows = val_df[val_df['iv'].notna()].index

    hidden_rows = np.random.choice(available_rows,size=int(0.2*len(available_rows)),replace=False)

    ground_truth = val_df.loc[hidden_rows,'iv'].values

    val_masked = val_df.copy()

    val_masked.loc[hidden_rows,'iv'] = np.nan

    return val_masked,hidden_rows,ground_truth

In [8]:
def eval_pred(actual,predicted):
    valid = ~np.isnan(predicted)

    mse = mean_squared_error(actual[valid],predicted[valid])
    coverage = valid.mean()

    print(f"MSE: {mse:6f}")
    print(f"Coverage: {coverage:6f}")

    return mse,coverage

In [9]:
import xgboost
import lightgbm
import catboost

In [10]:
from xgboost import XGBRegressor

fold_mses, fold_coverages, feature_importances = [],[],[]

drop_cols = ['iv','datetime','contract','option_type','date']

for fold in folds:
    train_df = df[df['datetime'].dt.date.isin(fold['train_dates'])].copy()

    val_df = df[df['datetime'].dt.date.isin(fold['val_dates'])].copy()

    val_masked, hidden_rows, ground_truth = make_holdout(val_df)

    # train data
    train_obs = train_df[train_df['iv'].notna()].copy()

    X_train = train_obs.drop(columns=drop_cols)
    y_train = train_obs['iv']

    # validation data
    X_val = val_masked.loc[hidden_rows].drop(columns=drop_cols)

    xgb_model = XGBRegressor(
        n_estimators= 500,
        learning_rate= 0.05,
        max_depth= 6,
        subsample= 0.8,
        colsample_bytree= 0.8,
        random_state= 2,
    )

    xgb_model.fit(X_train,y_train)
    xgb_pred = xgb_model.predict(X_val)
    
    xgb_mse, xgb_coverage = eval_pred(ground_truth,xgb_pred)

    fold_mses.append(xgb_mse)
    fold_coverages.append(xgb_coverage)
    feature_importances.append(xgb_model.feature_importances_)

print(f"xgb_mse: {np.mean(fold_mses):6f}")
print(f"xgb_coverage: {np.mean(fold_coverages):6f}")
print(f"feature importances: {feature_importances}")

MSE: 0.000082
Coverage: 1.000000
MSE: 0.000031
Coverage: 1.000000
xgb_mse: 0.000057
xgb_coverage: 1.000000
feature importances: [array([4.0105212e-04, 6.4687044e-03, 2.6302380e-04, 3.2407857e-04,
       4.5344996e-04, 4.8808707e-04, 4.0065980e-04, 1.5535585e-03,
       1.2179541e-03, 8.3658070e-04, 1.6398021e-03, 4.3233731e-04,
       9.5767819e-04, 1.1231116e-03, 2.4564939e-03, 3.0685433e-03,
       1.8700886e-03, 6.5499000e-02, 7.4701919e-03, 8.9218700e-04,
       1.9092827e-01, 6.5716275e-04, 7.0952487e-01, 6.8240991e-04,
       3.9073845e-04], dtype=float32), array([4.0197765e-04, 3.3393078e-03, 2.2084982e-04, 2.2894015e-04,
       5.1717670e-04, 4.3905640e-04, 4.4131003e-04, 1.2302756e-03,
       1.3631552e-03, 7.8754098e-04, 1.2207790e-03, 6.0431979e-04,
       9.9516194e-04, 1.3751175e-03, 2.0852732e-03, 3.0206181e-03,
       1.7931768e-03, 5.5677008e-02, 8.6484179e-03, 1.0532588e-03,
       2.4442613e-01, 6.2081829e-04, 6.6856349e-01, 5.3039298e-04,
       4.1644546e-04], dtype=float32)]

In [11]:
avg_importance = np.mean(feature_importances,axis=0)

importance_df = pd.DataFrame({
    'feature': X_train.columns,
    'importance': avg_importance
})

importance_df = importance_df.sort_values(by='importance',ascending=False)

importance_df

                  feature  importance
22        iv_roll_mean_10    0.689044
20         iv_roll_mean_5    0.217677
17       iv_neighbor_mean    0.060588
18  wide_iv_neighbor_mean    0.008059
1                  strike    0.004904
15         iv_neighbor_+1    0.003045
14         iv_neighbor_-1    0.002271
16         iv_neighbor_+2    0.001832
10      dist_from_atm_pct    0.001430
7               moneyness    0.001392
8           log_moneyness    0.001291
13         iv_neighbor_-2    0.001249
12            strike_rank    0.000976
19               iv_lag_1    0.000973
9           dist_from_atm    0.000812
21          iv_roll_std_5    0.000639
23             mean_ce_iv    0.000606
11                  is_ce    0.000518
4             day_of_week    0.000485
5        session_progress    0.000464
6          days_to_expiry    0.000421
24             mean_pe_iv    0.000404
0        underlying_price    0.000402
3                  minute    0.000277
2                    hour    0.000242

In [12]:
selected_features = importance_df[importance_df['importance']>=0.001]['feature'].tolist()

selected_features

['iv_roll_mean_10',
 'iv_roll_mean_5',
 'iv_neighbor_mean',
 'wide_iv_neighbor_mean',
 'strike',
 'iv_neighbor_+1',
 'iv_neighbor_-1',
 'iv_neighbor_+2',
 'dist_from_atm_pct',
 'moneyness',
 'log_moneyness',
 'iv_neighbor_-2']

In [13]:
df_pruned = df[selected_features+['iv','contract','option_type','date','datetime']].copy()
print(df_pruned.shape)
df_pruned.head()

(26325, 17)

,iv_roll_mean_10,iv_roll_mean_5,iv_neighbor_mean,wide_iv_neighbor_mean,strike,iv_neighbor_+1,iv_neighbor_-1,iv_neighbor_+2,dist_from_atm_pct,moneyness,log_moneyness,iv_neighbor_-2,iv,contract,option_type,date,datetime
0,NaN,NaN,0.12330,0.11741,25200,0.12330,NaN,0.11741,0.034914,0.965086,-0.035538,NaN,0.12662,NIFTY27JAN2625200CE,CE,2026-01-07,2026-01-07 09:15:00
1,NaN,NaN,NaN,NaN,25200,NaN,NaN,NaN,0.036012,0.963988,-0.036676,NaN,0.08632,NIFTY27JAN2625200CE,CE,2026-01-07,2026-01-07 09:20:00
2,NaN,0.106470,NaN,0.09514,25200,NaN,NaN,0.09514,0.035936,0.964064,-0.036598,NaN,0.09147,NIFTY27JAN2625200CE,CE,2026-01-07,2026-01-07 09:25:00
3,0.101470,0.101470,0.10842,0.11150,25200,0.10842,NaN,0.11150,0.035553,0.964447,-0.036200,NaN,0.10860,NIFTY27JAN2625200CE,CE,2026-01-07,2026-01-07 09:30:00
4,0.103252,0.103252,0.10538,0.12459,25200,0.10538,NaN,0.12459,0.035661,0.964339,-0.036313,NaN,0.10462,NIFTY27JAN2625200CE,CE,2026-01-07,2026-01-07 09:35:00

In [15]:
df_pruned['iv'].isna().sum()

np.int64(5279)

In [16]:
df_pruned.to_csv('C:/Users/Ayyan Aftab/Desktop/iv_surface_reconstruct/data/df_pruned.csv',index=False)

In [17]:
fold_mses, fold_coverages = [],[]

drop_cols = ['iv','datetime','contract','option_type','date']

for fold in folds:
    train_df = df_pruned[df_pruned['datetime'].dt.date.isin(fold['train_dates'])].copy()

    val_df = df_pruned[df_pruned['datetime'].dt.date.isin(fold['val_dates'])].copy()

    val_masked, hidden_rows, ground_truth = make_holdout(val_df)

    # train data
    train_obs = train_df[train_df['iv'].notna()].copy()

    X_train = train_obs.drop(columns=drop_cols)
    y_train = train_obs['iv']

    # validation data
    X_val = val_masked.loc[hidden_rows].drop(columns=drop_cols)

    xgb_model = XGBRegressor(
        n_estimators= 500,
        learning_rate= 0.05,
        max_depth= 6,
        subsample= 0.8,
        colsample_bytree= 0.8,
        random_state= 2,
    )

    xgb_model.fit(X_train,y_train)
    xgb_pred = xgb_model.predict(X_val)

    xgb_mse, xgb_coverage = eval_pred(ground_truth,xgb_pred)

    fold_mses.append(xgb_mse)
    fold_coverages.append(xgb_coverage)
    
print(f"xgbp_mse: {np.mean(fold_mses):6f}")
print(f"xgbp_coverage: {np.mean(fold_coverages):6f}")

MSE: 0.000081
Coverage: 1.000000
MSE: 0.000027
Coverage: 1.000000
xgbp_mse: 0.000054
xgbp_coverage: 1.000000

In [18]:
from lightgbm import LGBMRegressor

fold_mses, fold_coverages = [],[]

drop_cols = ['iv','datetime','contract','option_type','date']

for fold in folds:
    train_df = df_pruned[df_pruned['datetime'].dt.date.isin(fold['train_dates'])].copy()

    val_df = df_pruned[df_pruned['datetime'].dt.date.isin(fold['val_dates'])].copy()

    val_masked, hidden_rows, ground_truth = make_holdout(val_df)

    # train data
    train_obs = train_df[train_df['iv'].notna()].copy()

    X_train = train_obs.drop(columns=drop_cols)
    y_train = train_obs['iv']

    # validation data
    X_val = val_masked.loc[hidden_rows].drop(columns=drop_cols)

    lgbm_model = LGBMRegressor(
        n_estimators= 500,
        learning_rate= 0.05,
        max_depth= 6,
        subsample= 0.8,
        colsample_bytree= 0.8,
        random_state= 2,
    )

    lgbm_model.fit(X_train,y_train)
    lgbm_pred = lgbm_model.predict(X_val)
    
    lgbm_mse, lgbm_coverage = eval_pred(ground_truth,lgbm_pred)

    fold_mses.append(lgbm_mse)
    fold_coverages.append(lgbm_coverage)

print(f"MSE from both folds: {fold_mses}")
print(f"lgbm_mse: {np.mean(fold_mses):6f}")
print(f"lgbm_coverage: {np.mean(fold_coverages):6f}")

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001507 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2833
[LightGBM] [Info] Number of data points in the train set: 14546, number of used features: 12
[LightGBM] [Info] Start training from score 0.130303
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

In [19]:
from catboost import CatBoostRegressor

fold_mses, fold_coverages = [],[]

drop_cols = ['iv','datetime','contract','option_type','date']

for fold in folds:
    train_df = df_pruned[df_pruned['datetime'].dt.date.isin(fold['train_dates'])].copy()

    val_df = df_pruned[df_pruned['datetime'].dt.date.isin(fold['val_dates'])].copy()

    val_masked, hidden_rows, ground_truth = make_holdout(val_df)

    # train data
    train_obs = train_df[train_df['iv'].notna()].copy()

    X_train = train_obs.drop(columns=drop_cols)
    y_train = train_obs['iv']

    # validation data
    X_val = val_masked.loc[hidden_rows].drop(columns=drop_cols)

    cb_model = CatBoostRegressor(
        n_estimators= 500,
        learning_rate= 0.05,
        max_depth= 6,
        subsample= 0.8,
        random_state= 2,
    )
    
    cb_model.fit(X_train,y_train)
    cb_pred = cb_model.predict(X_val)

    cb_mse, cb_coverage = eval_pred(ground_truth,cb_pred)

    fold_mses.append(cb_mse)
    fold_coverages.append(cb_coverage)

print(f"MSE from both folds: {fold_mses}")
print(f"cb_mse: {np.mean(fold_mses):6f}")
print(f"cb_coverage: {np.mean(fold_coverages):6f}")

0:	learn: 0.0286213	total: 131ms	remaining: 1m 5s
1:	learn: 0.0273051	total: 142ms	remaining: 35.4s
2:	learn: 0.0260467	total: 150ms	remaining: 24.9s
3:	learn: 0.0248556	total: 158ms	remaining: 19.6s
4:	learn: 0.0237177	total: 162ms	remaining: 16s
5:	learn: 0.0226615	total: 166ms	remaining: 13.6s
6:	learn: 0.0216635	total: 170ms	remaining: 12s
7:	learn: 0.0206910	total: 173ms	remaining: 10.6s
8:	learn: 0.0197867	total: 176ms	remaining: 9.61s
9:	learn: 0.0189203	total: 179ms	remaining: 8.79s
10:	learn: 0.0180970	total: 182ms	remaining: 8.08s
11:	learn: 0.0172974	total: 184ms	remaining: 7.5s
12:	learn: 0.0165556	total: 187ms	remaining: 6.99s
13:	learn: 0.0158498	total: 189ms	remaining: 6.55s
14:	learn: 0.0151761	total: 191ms	remaining: 6.18s
15:	learn: 0.0145355	total: 193ms	remaining: 5.84s
16:	learn: 0.0139221	total: 195ms	remaining: 5.54s
17:	learn: 0.0133398	total: 197ms	remaining: 5.27s
18:	learn: 0.0127778	total: 199ms	remaining: 5.04s
19:	learn: 0.0122639	total: 201ms	remaining: 4.83s
20:	learn: 0.0117611	total: 203ms	remaining: 4.63s
21:	learn: 0.0112963	total: 205ms	remaining: 4.45s
22:	learn: 0.0108492	total: 207ms	remaining: 4.29s
23:	learn: 0.0104279	total: 209ms	remaining: 4.14s
24:	learn: 0.0100322	total: 211ms	remaining: 4.01s
25:	learn: 0.0096501	total: 213ms	remaining: 3.88s
26:	learn: 0.0092869	total: 216ms	remaining: 3.77s
27:	learn: 0.0089546	total: 218ms	remaining: 3.67s
28:	learn: 0.0086393	total: 221ms	remaining: 3.59s
29:	learn: 0.0083319	total: 224ms	remaining: 3.51s
30:	learn: 0.0080301	total: 226ms	remaining: 3.43s
31:	learn: 0.0077587	total: 229ms	remaining: 3.36s
32:	learn: 0.0075017	total: 232ms	remaining: 3.29s
33:	learn: 0.0072657	total: 235ms	remaining: 3.21s
34:	learn: 0.0070383	total: 237ms	remaining: 3.15s
35:	learn: 0.0068229	total: 240ms	remaining: 3.09s
36:	learn: 0.0066207	total: 242ms	remaining: 3.03s
37:	learn: 0.0064264	total: 245ms	remaining: 2.98s
38:	learn: 0.0062383	total: 248ms	remaining: 2.93s
39:	learn: 0.0060612	total: 251ms	remaining: 2.88s
40:	learn: 0.0058930	total: 254ms	remaining: 2.84s
41:	learn: 0.0057345	total: 256ms	remaining: 2.79s
42:	learn: 0.0055937	total: 259ms	remaining: 2.75s
43:	learn: 0.0054565	total: 262ms	remaining: 2.72s
44:	learn: 0.0053292	total: 265ms	remaining: 2.68s
45:	learn: 0.0052055	total: 268ms	remaining: 2.64s
46:	learn: 0.0050914	total: 271ms	remaining: 2.61s
47:	learn: 0.0049924	total: 273ms	remaining: 2.57s
48:	learn: 0.0048956	total: 277ms	remaining: 2.55s
49:	learn: 0.0048008	total: 280ms	remaining: 2.52s
50:	learn: 0.0047117	total: 282ms	remaining: 2.48s
51:	learn: 0.0046336	total: 286ms	remaining: 2.46s
52:	learn: 0.0045620	total: 288ms	remaining: 2.43s
53:	learn: 0.0044804	total: 291ms	remaining: 2.4s
54:	learn: 0.0044050	total: 294ms	remaining: 2.37s
55:	learn: 0.0043442	total: 296ms	remaining: 2.35s
56:	learn: 0.0042742	total: 299ms	remaining: 2.33s
57:	learn: 0.0042135	total: 302ms	remaining: 2.3s
58:	learn: 0.0041651	total: 304ms	remaining: 2.27s
59:	learn: 0.0041164	total: 307ms	remaining: 2.25s
60:	learn: 0.0040695	total: 310ms	remaining: 2.23s
61:	learn: 0.0040268	total: 313ms	remaining: 2.21s
62:	learn: 0.0039880	total: 316ms	remaining: 2.19s
63:	learn: 0.0039423	total: 319ms	remaining: 2.17s
64:	learn: 0.0039003	total: 321ms	remaining: 2.15s
65:	learn: 0.0038657	total: 324ms	remaining: 2.13s
66:	learn: 0.0038333	total: 326ms	remaining: 2.1s
67:	learn: 0.0038004	total: 328ms	remaining: 2.09s
68:	learn: 0.0037715	total: 331ms	remaining: 2.07s
69:	learn: 0.0037454	total: 333ms	remaining: 2.04s
70:	learn: 0.0037214	total: 335ms	remaining: 2.02s
71:	learn: 0.0036888	total: 337ms	remaining: 2s
72:	learn: 0.0036676	total: 340ms	remaining: 1.99s
73:	learn: 0.0036449	total: 342ms	remaining: 1.97s
74:	learn: 0.0036224	total: 345ms	remaining: 1.95s
75:	learn: 0.0036029	total: 347ms	remaining: 1.94s
76:	learn: 0.0035808	total: 349ms	remaining: 1.92s
77:	learn: 0.0035598	total: 352ms	remaining: 1.9s
78:	learn: 0.0035388	total: 355ms	remaining: 1.89s
79:	learn: 0.0035225	total: 357ms	remaining: 1.87s
80:	learn: 0.0035025	total: 359ms	remaining: 1.86s
81:	learn: 0.0034849	total: 363ms	remaining: 1.85s
82:	learn: 0.0034678	total: 365ms	remaining: 1.83s
83:	learn: 0.0034546	total: 368ms	remaining: 1.82s
84:	learn: 0.0034379	total: 371ms	remaining: 1.81s
85:	learn: 0.0034215	total: 373ms	remaining: 1.8s
86:	learn: 0.0034050	total: 377ms	remaining: 1.79s
87:	learn: 0.0033929	total: 380ms	remaining: 1.78s
88:	learn: 0.0033824	total: 382ms	remaining: 1.76s
89:	learn: 0.0033717	total: 385ms	remaining: 1.75s
90:	learn: 0.0033599	total: 387ms	remaining: 1.74s
91:	learn: 0.0033498	total: 389ms	remaining: 1.73s
92:	learn: 0.0033400	total: 392ms	remaining: 1.71s
93:	learn: 0.0033334	total: 394ms	remaining: 1.7s
94:	learn: 0.0033228	total: 397ms	remaining: 1.69s
95:	learn: 0.0033136	total: 399ms	remaining: 1.68s
96:	learn: 0.0033051	total: 402ms	remaining: 1.67s
97:	learn: 0.0032938	total: 404ms	remaining: 1.66s
98:	learn: 0.0032842	total: 407ms	remaining: 1.65s
99:	learn: 0.0032723	total: 409ms	remaining: 1.64s
100:	learn: 0.0032646	total: 411ms	remaining: 1.63s
101:	learn: 0.0032558	total: 413ms	remaining: 1.61s
102:	learn: 0.0032466	total: 416ms	remaining: 1.6s
103:	learn: 0.0032404	total: 418ms	remaining: 1.59s
104:	learn: 0.0032320	total: 420ms	remaining: 1.58s
105:	learn: 0.0032214	total: 423ms	remaining: 1.57s
106:	learn: 0.0032093	total: 425ms	remaining: 1.56s
107:	learn: 0.0031994	total: 427ms	remaining: 1.55s
108:	learn: 0.0031881	total: 429ms	remaining: 1.54s
109:	learn: 0.0031782	total: 431ms	remaining: 1.53s
110:	learn: 0.0031715	total: 434ms	remaining: 1.52s
111:	learn: 0.0031593	total: 436ms	remaining: 1.51s
112:	learn: 0.0031537	total: 438ms	remaining: 1.5s
113:	learn: 0.0031447	total: 441ms	remaining: 1.49s
114:	learn: 0.0031392	total: 443ms	remaining: 1.48s
115:	learn: 0.0031288	total: 446ms	remaining: 1.47s
116:	learn: 0.0031214	total: 448ms	remaining: 1.47s
117:	learn: 0.0031147	total: 450ms	remaining: 1.46s
118:	learn: 0.0031087	total: 453ms	remaining: 1.45s
119:	learn: 0.0031008	total: 455ms	remaining: 1.44s
120:	learn: 0.0030943	total: 457ms	remaining: 1.43s
121:	learn: 0.0030888	total: 459ms	remaining: 1.42s
122:	learn: 0.0030844	total: 462ms	remaining: 1.41s
123:	learn: 0.0030783	total: 464ms	remaining: 1.41s
124:	learn: 0.0030699	total: 466ms	remaining: 1.4s
125:	learn: 0.0030662	total: 469ms	remaining: 1.39s
126:	learn: 0.0030616	total: 471ms	remaining: 1.38s
127:	learn: 0.0030518	total: 473ms	remaining: 1.38s
128:	learn: 0.0030425	total: 476ms	remaining: 1.37s
129:	learn: 0.0030373	total: 478ms	remaining: 1.36s
130:	learn: 0.0030346	total: 480ms	remaining: 1.35s
131:	learn: 0.0030298	total: 482ms	remaining: 1.34s
132:	learn: 0.0030242	total: 484ms	remaining: 1.33s
133:	learn: 0.0030152	total: 486ms	remaining: 1.33s
134:	learn: 0.0030087	total: 489ms	remaining: 1.32s
135:	learn: 0.0030033	total: 491ms	remaining: 1.31s
136:	learn: 0.0030004	total: 493ms	remaining: 1.31s
137:	learn: 0.0029933	total: 495ms	remaining: 1.3s
138:	learn: 0.0029898	total: 497ms	remaining: 1.29s
139:	learn: 0.0029845	total: 500ms	remaining: 1.28s
140:	learn: 0.0029818	total: 502ms	remaining: 1.28s
141:	learn: 0.0029759	total: 504ms	remaining: 1.27s
142:	learn: 0.0029697	total: 506ms	remaining: 1.26s
143:	learn: 0.0029639	total: 508ms	remaining: 1.26s
144:	learn: 0.0029564	total: 510ms	remaining: 1.25s
145:	learn: 0.0029527	total: 513ms	remaining: 1.24s
146:	learn: 0.0029462	total: 515ms	remaining: 1.24s
147:	learn: 0.0029425	total: 517ms	remaining: 1.23s
148:	learn: 0.0029377	total: 519ms	remaining: 1.22s
149:	learn: 0.0029349	total: 522ms	remaining: 1.22s
150:	learn: 0.0029289	total: 524ms	remaining: 1.21s
151:	learn: 0.0029266	total: 526ms	remaining: 1.21s
152:	learn: 0.0029216	total: 529ms	remaining: 1.2s
153:	learn: 0.0029139	total: 531ms	remaining: 1.19s
154:	learn: 0.0029102	total: 533ms	remaining: 1.19s
155:	learn: 0.0029034	total: 535ms	remaining: 1.18s
156:	learn: 0.0028978	total: 538ms	remaining: 1.17s
157:	learn: 0.0028920	total: 540ms	remaining: 1.17s
158:	learn: 0.0028882	total: 543ms	remaining: 1.16s
159:	learn: 0.0028823	total: 545ms	remaining: 1.16s
160:	learn: 0.0028746	total: 548ms	remaining: 1.15s
161:	learn: 0.0028714	total: 550ms	remaining: 1.15s
162:	learn: 0.0028677	total: 552ms	remaining: 1.14s
163:	learn: 0.0028609	total: 555ms	remaining: 1.14s
164:	learn: 0.0028563	total: 557ms	remaining: 1.13s
165:	learn: 0.0028505	total: 560ms	remaining: 1.13s
166:	learn: 0.0028446	total: 562ms	remaining: 1.12s
167:	learn: 0.0028425	total: 564ms	remaining: 1.11s
168:	learn: 0.0028395	total: 566ms	remaining: 1.11s
169:	learn: 0.0028336	total: 569ms	remaining: 1.1s
170:	learn: 0.0028278	total: 571ms	remaining: 1.1s
171:	learn: 0.0028239	total: 573ms	remaining: 1.09s
172:	learn: 0.0028188	total: 575ms	remaining: 1.09s
173:	learn: 0.0028155	total: 577ms	remaining: 1.08s
174:	learn: 0.0028105	total: 579ms	remaining: 1.07s
175:	learn: 0.0028056	total: 581ms	remaining: 1.07s
176:	learn: 0.0028000	total: 584ms	remaining: 1.06s
177:	learn: 0.0027974	total: 586ms	remaining: 1.06s
178:	learn: 0.0027929	total: 588ms	remaining: 1.05s
179:	learn: 0.0027865	total: 590ms	remaining: 1.05s
180:	learn: 0.0027806	total: 593ms	remaining: 1.04s
181:	learn: 0.0027763	total: 595ms	remaining: 1.04s
182:	learn: 0.0027715	total: 597ms	remaining: 1.03s
183:	learn: 0.0027691	total: 600ms	remaining: 1.03s
184:	learn: 0.0027645	total: 602ms	remaining: 1.02s
185:	learn: 0.0027589	total: 604ms	remaining: 1.02s
186:	learn: 0.0027567	total: 607ms	remaining: 1.01s
187:	learn: 0.0027527	total: 609ms	remaining: 1.01s
188:	learn: 0.0027479	total: 612ms	remaining: 1.01s
189:	learn: 0.0027454	total: 614ms	remaining: 1s
190:	learn: 0.0027439	total: 616ms	remaining: 997ms
191:	learn: 0.0027412	total: 618ms	remaining: 992ms
192:	learn: 0.0027364	total: 620ms	remaining: 986ms
193:	learn: 0.0027302	total: 622ms	remaining: 981ms
194:	learn: 0.0027280	total: 625ms	remaining: 977ms
195:	learn: 0.0027251	total: 627ms	remaining: 972ms
196:	learn: 0.0027201	total: 629ms	remaining: 967ms
197:	learn: 0.0027159	total: 631ms	remaining: 962ms
198:	learn: 0.0027121	total: 633ms	remaining: 958ms
199:	learn: 0.0027089	total: 635ms	remaining: 953ms
200:	learn: 0.0027038	total: 637ms	remaining: 948ms
201:	learn: 0.0027015	total: 640ms	remaining: 944ms
202:	learn: 0.0026978	total: 642ms	remaining: 939ms
203:	learn: 0.0026949	total: 644ms	remaining: 934ms
204:	learn: 0.0026914	total: 646ms	remaining: 930ms
205:	learn: 0.0026878	total: 649ms	remaining: 926ms
206:	learn: 0.0026840	total: 651ms	remaining: 922ms
207:	learn: 0.0026816	total: 653ms	remaining: 917ms
208:	learn: 0.0026762	total: 656ms	remaining: 913ms
209:	learn: 0.0026716	total: 658ms	remaining: 909ms
210:	learn: 0.0026676	total: 660ms	remaining: 904ms
211:	learn: 0.0026653	total: 662ms	remaining: 900ms
212:	learn: 0.0026623	total: 665ms	remaining: 896ms
213:	learn: 0.0026581	total: 667ms	remaining: 891ms
214:	learn: 0.0026559	total: 669ms	remaining: 886ms
215:	learn: 0.0026509	total: 671ms	remaining: 882ms
216:	learn: 0.0026488	total: 673ms	remaining: 878ms
217:	learn: 0.0026450	total: 675ms	remaining: 873ms
218:	learn: 0.0026414	total: 677ms	remaining: 869ms
219:	learn: 0.0026378	total: 680ms	remaining: 866ms
220:	learn: 0.0026332	total: 683ms	remaining: 862ms
221:	learn: 0.0026292	total: 685ms	remaining: 857ms
222:	learn: 0.0026244	total: 687ms	remaining: 853ms
223:	learn: 0.0026213	total: 689ms	remaining: 849ms
224:	learn: 0.0026189	total: 691ms	remaining: 845ms
225:	learn: 0.0026167	total: 693ms	remaining: 841ms
226:	learn: 0.0026111	total: 696ms	remaining: 837ms
227:	learn: 0.0026077	total: 700ms	remaining: 835ms
228:	learn: 0.0026052	total: 704ms	remaining: 833ms
229:	learn: 0.0026030	total: 706ms	remaining: 828ms
230:	learn: 0.0026003	total: 708ms	remaining: 824ms
231:	learn: 0.0025953	total: 710ms	remaining: 820ms
232:	learn: 0.0025929	total: 712ms	remaining: 816ms
233:	learn: 0.0025909	total: 714ms	remaining: 812ms
234:	learn: 0.0025874	total: 717ms	remaining: 808ms
235:	learn: 0.0025861	total: 719ms	remaining: 804ms
236:	learn: 0.0025824	total: 721ms	remaining: 800ms
237:	learn: 0.0025794	total: 723ms	remaining: 796ms
238:	learn: 0.0025773	total: 725ms	remaining: 792ms
239:	learn: 0.0025733	total: 728ms	remaining: 789ms
240:	learn: 0.0025704	total: 731ms	remaining: 785ms
241:	learn: 0.0025664	total: 734ms	remaining: 782ms
242:	learn: 0.0025623	total: 737ms	remaining: 779ms
243:	learn: 0.0025600	total: 739ms	remaining: 775ms
244:	learn: 0.0025571	total: 741ms	remaining: 772ms
245:	learn: 0.0025549	total: 744ms	remaining: 768ms
246:	learn: 0.0025511	total: 746ms	remaining: 764ms
247:	learn: 0.0025490	total: 749ms	remaining: 761ms
248:	learn: 0.0025463	total: 751ms	remaining: 758ms
249:	learn: 0.0025425	total: 754ms	remaining: 754ms
250:	learn: 0.0025388	total: 756ms	remaining: 750ms
251:	learn: 0.0025366	total: 759ms	remaining: 747ms
252:	learn: 0.0025355	total: 762ms	remaining: 743ms
253:	learn: 0.0025336	total: 764ms	remaining: 740ms
254:	learn: 0.0025316	total: 767ms	remaining: 737ms
255:	learn: 0.0025285	total: 769ms	remaining: 733ms
256:	learn: 0.0025265	total: 772ms	remaining: 730ms
257:	learn: 0.0025236	total: 774ms	remaining: 726ms
258:	learn: 0.0025217	total: 776ms	remaining: 722ms
259:	learn: 0.0025196	total: 779ms	remaining: 719ms
260:	learn: 0.0025178	total: 781ms	remaining: 715ms
261:	learn: 0.0025148	total: 783ms	remaining: 712ms
262:	learn: 0.0025116	total: 786ms	remaining: 708ms
263:	learn: 0.0025070	total: 788ms	remaining: 704ms
264:	learn: 0.0025032	total: 792ms	remaining: 702ms
265:	learn: 0.0025009	total: 794ms	remaining: 699ms
266:	learn: 0.0024973	total: 796ms	remaining: 695ms
267:	learn: 0.0024936	total: 799ms	remaining: 692ms
268:	learn: 0.0024905	total: 802ms	remaining: 688ms
269:	learn: 0.0024888	total: 804ms	remaining: 685ms
270:	learn: 0.0024850	total: 807ms	remaining: 682ms
271:	learn: 0.0024832	total: 809ms	remaining: 678ms
272:	learn: 0.0024815	total: 811ms	remaining: 675ms
273:	learn: 0.0024793	total: 814ms	remaining: 671ms
274:	learn: 0.0024763	total: 816ms	remaining: 668ms
275:	learn: 0.0024745	total: 819ms	remaining: 664ms
276:	learn: 0.0024717	total: 821ms	remaining: 661ms
277:	learn: 0.0024681	total: 823ms	remaining: 658ms
278:	learn: 0.0024665	total: 825ms	remaining: 654ms
279:	learn: 0.0024635	total: 828ms	remaining: 650ms
280:	learn: 0.0024617	total: 830ms	remaining: 647ms
281:	learn: 0.0024582	total: 832ms	remaining: 644ms
282:	learn: 0.0024548	total: 835ms	remaining: 640ms
283:	learn: 0.0024534	total: 837ms	remaining: 637ms
284:	learn: 0.0024517	total: 840ms	remaining: 633ms
285:	learn: 0.0024494	total: 842ms	remaining: 630ms
286:	learn: 0.0024478	total: 845ms	remaining: 627ms
287:	learn: 0.0024444	total: 847ms	remaining: 624ms
288:	learn: 0.0024413	total: 850ms	remaining: 620ms
289:	learn: 0.0024399	total: 852ms	remaining: 617ms
290:	learn: 0.0024366	total: 855ms	remaining: 614ms
291:	learn: 0.0024354	total: 858ms	remaining: 611ms
292:	learn: 0.0024338	total: 860ms	remaining: 608ms
293:	learn: 0.0024326	total: 863ms	remaining: 604ms
294:	learn: 0.0024310	total: 865ms	remaining: 601ms
295:	learn: 0.0024282	total: 867ms	remaining: 598ms
296:	learn: 0.0024241	total: 870ms	remaining: 595ms
297:	learn: 0.0024218	total: 872ms	remaining: 591ms
298:	learn: 0.0024187	total: 875ms	remaining: 588ms
299:	learn: 0.0024162	total: 877ms	remaining: 585ms
300:	learn: 0.0024136	total: 880ms	remaining: 582ms
301:	learn: 0.0024117	total: 882ms	remaining: 578ms
302:	learn: 0.0024105	total: 884ms	remaining: 575ms
303:	learn: 0.0024092	total: 886ms	remaining: 571ms
304:	learn: 0.0024077	total: 888ms	remaining: 568ms
305:	learn: 0.0024064	total: 890ms	remaining: 564ms
306:	learn: 0.0024049	total: 893ms	remaining: 561ms
307:	learn: 0.0024031	total: 895ms	remaining: 558ms
308:	learn: 0.0024018	total: 897ms	remaining: 554ms
309:	learn: 0.0023991	total: 899ms	remaining: 551ms
310:	learn: 0.0023964	total: 902ms	remaining: 548ms
311:	learn: 0.0023933	total: 904ms	remaining: 545ms
312:	learn: 0.0023921	total: 906ms	remaining: 541ms
313:	learn: 0.0023910	total: 908ms	remaining: 538ms
314:	learn: 0.0023882	total: 910ms	remaining: 535ms
315:	learn: 0.0023856	total: 913ms	remaining: 531ms
316:	learn: 0.0023842	total: 915ms	remaining: 528ms
317:	learn: 0.0023820	total: 917ms	remaining: 525ms
318:	learn: 0.0023808	total: 919ms	remaining: 522ms
319:	learn: 0.0023792	total: 921ms	remaining: 518ms
320:	learn: 0.0023783	total: 924ms	remaining: 515ms
321:	learn: 0.0023762	total: 926ms	remaining: 512ms
322:	learn: 0.0023750	total: 928ms	remaining: 509ms
323:	learn: 0.0023727	total: 930ms	remaining: 505ms
324:	learn: 0.0023701	total: 933ms	remaining: 502ms
325:	learn: 0.0023685	total: 935ms	remaining: 499ms
326:	learn: 0.0023673	total: 937ms	remaining: 496ms
327:	learn: 0.0023647	total: 939ms	remaining: 493ms
328:	learn: 0.0023637	total: 942ms	remaining: 490ms
329:	learn: 0.0023618	total: 944ms	remaining: 486ms
330:	learn: 0.0023589	total: 946ms	remaining: 483ms
331:	learn: 0.0023567	total: 949ms	remaining: 480ms
332:	learn: 0.0023553	total: 951ms	remaining: 477ms
333:	learn: 0.0023526	total: 953ms	remaining: 474ms
334:	learn: 0.0023517	total: 956ms	remaining: 471ms
335:	learn: 0.0023503	total: 958ms	remaining: 467ms
336:	learn: 0.0023485	total: 960ms	remaining: 464ms
337:	learn: 0.0023479	total: 962ms	remaining: 461ms
338:	learn: 0.0023462	total: 964ms	remaining: 458ms
339:	learn: 0.0023450	total: 966ms	remaining: 455ms
340:	learn: 0.0023436	total: 969ms	remaining: 452ms
341:	learn: 0.0023416	total: 971ms	remaining: 448ms
342:	learn: 0.0023405	total: 973ms	remaining: 445ms
343:	learn: 0.0023388	total: 975ms	remaining: 442ms
344:	learn: 0.0023364	total: 977ms	remaining: 439ms
345:	learn: 0.0023340	total: 979ms	remaining: 436ms
346:	learn: 0.0023326	total: 981ms	remaining: 433ms
347:	learn: 0.0023311	total: 984ms	remaining: 430ms
348:	learn: 0.0023303	total: 985ms	remaining: 426ms
349:	learn: 0.0023270	total: 988ms	remaining: 424ms
350:	learn: 0.0023260	total: 990ms	remaining: 420ms
351:	learn: 0.0023251	total: 992ms	remaining: 417ms
352:	learn: 0.0023244	total: 994ms	remaining: 414ms
353:	learn: 0.0023220	total: 997ms	remaining: 411ms
354:	learn: 0.0023199	total: 999ms	remaining: 408ms
355:	learn: 0.0023193	total: 1s	remaining: 405ms
356:	learn: 0.0023172	total: 1s	remaining: 402ms
357:	learn: 0.0023142	total: 1s	remaining: 399ms
358:	learn: 0.0023130	total: 1.01s	remaining: 396ms
359:	learn: 0.0023111	total: 1.01s	remaining: 393ms
360:	learn: 0.0023089	total: 1.01s	remaining: 390ms
361:	learn: 0.0023079	total: 1.01s	remaining: 387ms
362:	learn: 0.0023062	total: 1.02s	remaining: 384ms
363:	learn: 0.0023049	total: 1.02s	remaining: 381ms
364:	learn: 0.0023024	total: 1.02s	remaining: 378ms
365:	learn: 0.0023004	total: 1.02s	remaining: 375ms
366:	learn: 0.0022991	total: 1.02s	remaining: 371ms
367:	learn: 0.0022972	total: 1.03s	remaining: 369ms
368:	learn: 0.0022965	total: 1.03s	remaining: 366ms
369:	learn: 0.0022946	total: 1.03s	remaining: 363ms
370:	learn: 0.0022940	total: 1.03s	remaining: 359ms
371:	learn: 0.0022915	total: 1.04s	remaining: 357ms
372:	learn: 0.0022887	total: 1.04s	remaining: 354ms
373:	learn: 0.0022869	total: 1.04s	remaining: 351ms
374:	learn: 0.0022848	total: 1.04s	remaining: 348ms
375:	learn: 0.0022830	total: 1.04s	remaining: 345ms
376:	learn: 0.0022817	total: 1.05s	remaining: 342ms
377:	learn: 0.0022800	total: 1.05s	remaining: 339ms
378:	learn: 0.0022777	total: 1.05s	remaining: 336ms
379:	learn: 0.0022766	total: 1.05s	remaining: 333ms
380:	learn: 0.0022742	total: 1.06s	remaining: 330ms
381:	learn: 0.0022723	total: 1.06s	remaining: 327ms
382:	learn: 0.0022712	total: 1.06s	remaining: 324ms
383:	learn: 0.0022702	total: 1.06s	remaining: 321ms
384:	learn: 0.0022685	total: 1.06s	remaining: 318ms
385:	learn: 0.0022676	total: 1.07s	remaining: 315ms
386:	learn: 0.0022648	total: 1.07s	remaining: 312ms